server:
  port: 8087
spring:
  application:
    name: sms-service
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
leyou:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:     # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate:  # 模板名称