server:
  port: 8087
spring:
  application:
    name: sms-service
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
leyou:
  sms:
    accessKeyId: LTAIhoiIDe5keLyE # 你自己的accessKeyId
    accessKeySecret: TdsDfEhDIvAG4rQV72WNG9v3Zln85O    # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_172887085 # 模板名称